name: Deploy Flutter Web App to Firebase Hosting

on:
  push:
    branches:
      - main  # Trigger workflow when changes are pushed to the main branch
    paths:
      - 'summative/FlutterApp/carpriceapp/**'  # Only trigger when this directory changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: stable

    - name: Build Flutter for web
      working-directory: summative/FlutterApp/carpriceapp
      run: flutter build web

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy to Firebase Hosting
      working-directory: summative/FlutterApp/carpriceapp
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: firebase deploy --only hosting
